In [3]:
def superset(list_):
    sets = [set([])]
    for n in list_:
        sets.extend([s | {n} for s in sets])
    return sets

In [4]:
numbers = ['a','b']
ss = superset(numbers)
print(ss)

[set(), {'a'}, {'b'}, {'a', 'b'}]


In [8]:
[''.join(s) for s in ss]

['', 'a', 'b', 'ab']

In [9]:
all_ = {'1': [1,2], '2': [2,3], '3': [3,4], '4': [4,5], '5': [5,6]}

In [10]:
import random

In [13]:
s = random.sample(list(all_), 3)
s

['3', '2', '1']

In [15]:
set(list(all_)) - set(s)

{'4', '5'}

In [17]:
ss = superset(['f','d','b','t','c'])
print(ss)
print(len(ss))

[set(), {'f'}, {'d'}, {'d', 'f'}, {'b'}, {'b', 'f'}, {'b', 'd'}, {'b', 'd', 'f'}, {'t'}, {'t', 'f'}, {'t', 'd'}, {'t', 'd', 'f'}, {'b', 't'}, {'t', 'b', 'f'}, {'b', 'd', 't'}, {'t', 'b', 'd', 'f'}, {'c'}, {'c', 'f'}, {'c', 'd'}, {'c', 'd', 'f'}, {'c', 'b'}, {'c', 'b', 'f'}, {'c', 'b', 'd'}, {'c', 'b', 'd', 'f'}, {'c', 't'}, {'c', 't', 'f'}, {'c', 't', 'd'}, {'c', 't', 'd', 'f'}, {'c', 'b', 't'}, {'t', 'c', 'b', 'f'}, {'c', 'b', 'd', 't'}, {'t', 'b', 'd', 'f', 'c'}]
32


In [18]:
ss = superset(['f','d','b','c'])
print(ss)
print(len(ss))

[set(), {'f'}, {'d'}, {'d', 'f'}, {'b'}, {'b', 'f'}, {'b', 'd'}, {'b', 'd', 'f'}, {'c'}, {'c', 'f'}, {'c', 'd'}, {'c', 'd', 'f'}, {'c', 'b'}, {'c', 'b', 'f'}, {'c', 'b', 'd'}, {'c', 'b', 'd', 'f'}]
16


In [2]:
import numpy as np


In [3]:
from PIL import Image


In [4]:
with Image.open('Images/6b64913854b27c53.jpg') as img:
    a = np.array(img)
    print(a.shape)

(250, 250, 3)


In [5]:
a[0,0,2] = 4

In [6]:
t = [ np.zeros((2, 3, 250, 250, 3)) ]*5

In [7]:
t[0][1,2,:] = a

In [8]:
b = np.array([1,2,3])

In [32]:
np.outer(b, np.ones(5)).reshape(len(b)*5)

array([1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 3., 3., 3., 3., 3.])

In [43]:
t = np.load('TrainDatasets/train0.npy')

In [44]:
classes = np.load('TrainDatasets/classes.npy')

In [45]:
classes[0]

13170.0

In [46]:
t.shape

(18720, 224, 224, 3)

In [47]:
for i in range(100):
    print(t[i])

[[[189 196 225]
  [163 170 199]
  [114 121 150]
  ...
  [ 28  48 117]
  [ 26  46 115]
  [ 26  46 115]]

 [[169 176 205]
  [127 134 163]
  [ 64  71 100]
  ...
  [ 28  48 117]
  [ 26  46 115]
  [ 26  46 115]]

 [[138 147 176]
  [ 95 104 133]
  [ 42  51  80]
  ...
  [ 28  48 117]
  [ 26  46 115]
  [ 26  46 115]]

 ...

 [[102 103 107]
  [100 101 105]
  [ 98  99 103]
  ...
  [ 69 119 107]
  [ 68 122 108]
  [ 93 150 135]]

 [[106 107 111]
  [109 110 114]
  [ 99 100 104]
  ...
  [ 93 153 145]
  [ 79 142 133]
  [ 85 152 143]]

 [[ 86  87  89]
  [ 92  93  95]
  [ 87  88  92]
  ...
  [ 89 143 143]
  [ 32  92  92]
  [ 48 112 112]]]
[[[ 26  46 115]
  [ 26  46 115]
  [ 28  48 117]
  ...
  [114 121 150]
  [163 170 199]
  [189 196 225]]

 [[ 26  46 115]
  [ 26  46 115]
  [ 28  48 117]
  ...
  [ 64  71 100]
  [127 134 163]
  [169 176 205]]

 [[ 26  46 115]
  [ 26  46 115]
  [ 28  48 117]
  ...
  [ 42  51  80]
  [ 95 104 133]
  [138 147 176]]

 ...

 [[ 93 150 135]
  [ 68 122 108]
  [ 69 119 107]
  ..

In [31]:
t[0].shape

(224, 224, 3)