In [3]:
def superset(list_):
    sets = [set([])]
    for n in list_:
        sets.extend([s | {n} for s in sets])
    return sets

In [4]:
numbers = ['a','b']
ss = superset(numbers)
print(ss)

[set(), {'a'}, {'b'}, {'a', 'b'}]


In [8]:
[''.join(s) for s in ss]

['', 'a', 'b', 'ab']

In [9]:
all_ = {'1': [1,2], '2': [2,3], '3': [3,4], '4': [4,5], '5': [5,6]}

In [10]:
import random

In [13]:
s = random.sample(list(all_), 3)
s

['3', '2', '1']

In [15]:
set(list(all_)) - set(s)

{'4', '5'}

In [17]:
ss = superset(['f','d','b','t','c'])
print(ss)
print(len(ss))

[set(), {'f'}, {'d'}, {'d', 'f'}, {'b'}, {'b', 'f'}, {'b', 'd'}, {'b', 'd', 'f'}, {'t'}, {'t', 'f'}, {'t', 'd'}, {'t', 'd', 'f'}, {'b', 't'}, {'t', 'b', 'f'}, {'b', 'd', 't'}, {'t', 'b', 'd', 'f'}, {'c'}, {'c', 'f'}, {'c', 'd'}, {'c', 'd', 'f'}, {'c', 'b'}, {'c', 'b', 'f'}, {'c', 'b', 'd'}, {'c', 'b', 'd', 'f'}, {'c', 't'}, {'c', 't', 'f'}, {'c', 't', 'd'}, {'c', 't', 'd', 'f'}, {'c', 'b', 't'}, {'t', 'c', 'b', 'f'}, {'c', 'b', 'd', 't'}, {'t', 'b', 'd', 'f', 'c'}]
32


In [18]:
ss = superset(['f','d','b','c'])
print(ss)
print(len(ss))

[set(), {'f'}, {'d'}, {'d', 'f'}, {'b'}, {'b', 'f'}, {'b', 'd'}, {'b', 'd', 'f'}, {'c'}, {'c', 'f'}, {'c', 'd'}, {'c', 'd', 'f'}, {'c', 'b'}, {'c', 'b', 'f'}, {'c', 'b', 'd'}, {'c', 'b', 'd', 'f'}]
16


In [2]:
import numpy as np


In [3]:
from PIL import Image


In [4]:
with Image.open('Images/6b64913854b27c53.jpg') as img:
    a = np.array(img)
    print(a.shape)

(250, 250, 3)


In [5]:
a[0,0,2] = 4

In [6]:
t = [ np.zeros((2, 3, 250, 250, 3)) ]*5

In [7]:
t[0][1,2,:] = a

In [8]:
b = np.array([1,2,3])

In [32]:
np.outer(b, np.ones(5)).reshape(len(b)*5)

array([1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 3., 3., 3., 3., 3.])

In [33]:
t = np.load('TrainDatasets/train0.npy')

In [34]:
classes = np.load('TrainDatasets/classes.npy')

In [35]:
classes[0]

5921.0

In [36]:
t.shape

(18720, 224, 224, 3)

In [37]:
for i in range(100):
    print(t[i])

[[[  29   47   21]
  [  43   58   35]
  [  43   58   35]
  ...
  [  31 -107  -17]
  [  13 -124  -34]
  [  32 -103  -12]]

 [[  40   58   34]
  [  44   59   36]
  [  45   60   37]
  ...
  [  33 -105  -15]
  [  28 -109  -19]
  [  44  -91   -1]]

 [[  48   66   42]
  [  44   59   36]
  [  43   58   37]
  ...
  [  32 -105  -15]
  [  15 -120  -31]
  [  29 -103  -13]]

 ...

 [[  29   43   30]
  [  18   32   19]
  [  18   32   19]
  ...
  [  44   65   66]
  [  51   72   73]
  [  46   67   70]]

 [[  22   35   25]
  [  23   37   24]
  [  12   26   13]
  ...
  [  42   63   64]
  [  34   55   58]
  [  40   61   64]]

 [[  21   37   26]
  [  24   40   29]
  [  14   30   17]
  ...
  [  47   68   71]
  [  37   58   61]
  [  43   64   69]]]
[[[  32 -103  -12]
  [  13 -124  -34]
  [  31 -107  -17]
  ...
  [  43   58   35]
  [  43   58   35]
  [  29   47   21]]

 [[  44  -91   -1]
  [  28 -109  -19]
  [  33 -105  -15]
  ...
  [  45   60   37]
  [  44   59   36]
  [  40   58   34]]

 [[  29 -103  -13]

In [31]:
t[0].shape

(224, 224, 3)